inksink_src_dir: "{{ playbook_dir }}/../../src/inksink"
inksink_dest_dir: /opt/inksink
inksink_vendor_dir: /opt/waveshare-vendor
inksink_config_dir: /etc/inksink
inksink_wrapper: /usr/local/bin/inksink
inksink_service: inksink

ankiweb_username: "{{ vault_ankiweb_username }}"
ankiweb_password: "{{ vault_ankiweb_password }}"
wifi_password: "{{ vault_wifi_password }}"
