[project]
name = "inksink"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "Pillow",
    "PyYAML>=6.0,<7.0",
    "Jinja2>=3.0",
    "requests",
    "smbus2>=0.6.1,<0.7",
    "anki==25.9.4",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-mock",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.black]
line-length = 88
target-version = ["py313"]
exclude = "vendor/"

[tool.ruff]
line-length = 88
target-version = "py313"
exclude = ["vendor"]

[tool.ruff.lint]
select = ["E", "F", "W", "I"]  # pycodestyle, pyflakes, isort

[tool.pyright]
pythonVersion = "3.13"
venvPath = "."
venv = ".venv"
typeCheckingMode = "standard"
exclude = ["vendor"]
reportMissingModuleSource = false
